//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleExerciser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleExerciser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Endorse.Ini file for 
        /////     SS Expert/Pro/Value 
        /////     SNDP 
        /////--------------------------------------------------------
        /// 
        ///[MJEREAR]
        /// 
        ///// NOPAUSEATENDORSELOOP
        ///// This tells the sorter not to pause if the DocProcess 
        ///// command is not received in time.  Using this works 
        ///// best if you are either using a pre-set endorsement 
        ///// or do not plan on endorsing at all and you are not 
        ///// changing the doctype(snippet area) on  per doc basis.
        ///// The following values can be selected:
        ///// 0 = Pause at [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string endorse {
            get {
                return ResourceManager.GetString("endorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Image.Ini file for 
        /////     NDP 30/60/110 
        /////     NDP 250/300/500/600/Quantum 
        /////     NDP 85/1100/1800 
        /////     SS Adaptive/Expert/Pro/Value 
        /////     SNDP 
        /////--------------------------------------------------------
        /// 
        ///[GENERAL]
        /// 
        ///// 200DPI
        ///// (Applies only to the SNDP and SS Expert/Pro/Value.) 
        ///// This specifies that images are scaled from 240 to 200
        ///// DPI.  This applies to all images.  
        /////(Only valid for SNDPs manufactured after Nov 2003 
        ///// using CAPI 7.0 or higher).
        ///// The following value [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Reader.Ini file for 
        /////     SS Expert/Pro/Value 
        /////     SNDP 
        /////--------------------------------------------------------
        /// 
        ///[GENERAL]
        /// 
        ///// MICRCOMBINED
        ///// Only valid for the reader whose READERID = 8 or 9.  
        ///// This setting determines how the reader should determine
        ///// which read result to use for each character in the 
        ///// codeline if algorithm 1 differs from algorithm 2.
        ///// The following values can be selected:
        ///// 0 = Minimize the number of Can&apos;t Reads. This may result
        /////     in a higher nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reader {
            get {
                return ResourceManager.GetString("reader", resourceCulture);
            }
        }
    }
}
